### ISSUE TITLE
error: kex_exchange_identification: Connection closed by remote host

### ISSUE THREAD

**Issue by gunalabs** [dwyl/gogs-server#4]
Hi. I tried deploying it in fly.io and the log says the following:

![image](https://user-images.githubusercontent.com/67857588/222946731-c5d4228e-648d-4ffa-b09f-afc198ed1e4d.png)

![image](https://user-images.githubusercontent.com/67857588/222946571-92b5f0dc-3386-4b61-bc1d-7cc8b69c3a9f.png)

When I try to launch in browser, nothing comes up saying: **Unable to connect**.

**Comment by nelsonic** [comment]
Hi @gunalabs 👋 
We are not experts in deploying to `Fly.io`. 💭 
We've attempted to document our steps for a successful deployment. 📝 
But ultimately if something is not working, your best bet for "support" is to open a topic on: https://community.fly.io 🔗 
where one of the community (or paid staff) can help you. 🤞

**Comment by gunalabs** [comment]
Hi. Thanks for your reply. I just have a question.
Did`app.ini` autogenerate during deployment? 
For me it didn't so I'm not sure if I have to add it myself manually somehow.
Thanks.

**Comment by gunalabs** [comment]
Update: Hi. Just found the issue. It was a misconfiguration in network and that error has nothing to do with the above output.
https://community.fly.io/t/tried-to-deply-gogs-gogs-git-service-and-got-sshd-22-already-in-use-and-error-kex-exchange-identification-connection-closed-by-remote-host/11245

**Comment by nelsonic** [comment]
@gunalabs glad you figured it out. 👌 
If this repo was useful to you, please ⭐ 🙏
